version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:50051
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "127.0.0.1:50051:50051"
    env_file:
      - ./.env.dev
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    external:
      name: localdev

# how compose file works
# https://docs.docker.com/compose/compose-file/
