# Generated by Django 3.0.7 on 2020-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20200807_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svg_post',
            name='color',
            field=models.CharField(choices=[('Feminine', '#FF69B4'), ('Masculine', '#464646'), ('default', '#696969')], default='default', max_length=15),
        ),
        migrations.AlterField(
            model_name='svg_post',
            name='font',
            field=models.CharField(choices=[('SpaceGrotesk-Bold, Space Grotesk', 'SpaceGrotesk-Bold, Space Grotesk')], default='default', max_length=50),
        ),
    ]
