# Generated by Django 3.0.7 on 2020-08-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20200808_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svg_post',
            name='color',
            field=models.CharField(choices=[('Feminine', '#FF69B4'), ('Masculine', '#464646'), ('Other', '#696969')], max_length=15),
        ),
        migrations.AlterField(
            model_name='svg_post',
            name='style',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=15),
        ),
        migrations.AlterField(
            model_name='svg_post',
            name='symbol',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100),
        ),
        migrations.AlterField(
            model_name='svg_post',
            name='tag',
            field=models.CharField(choices=[('Nice', 'Nice'), ('Cool', 'Cool'), ('Masculine', 'Masculine')], max_length=100),
        ),
    ]
