# Generated by Django 3.0.7 on 2020-08-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20200808_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVG_FILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.FileField(upload_to='mediafiles/svg')),
            ],
        ),
        migrations.AlterField(
            model_name='svg_post',
            name='color',
            field=models.CharField(choices=[('Feminine', '#FF69B4'), ('Masculine', '#464646'), ('Other', '#696969'), ('Yellow', '#6619FF')], default='#696969', max_length=15),
        ),
    ]
