# Generated by Django 3.0.7 on 2020-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20200809_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='svg_post',
            name='templates',
            field=models.CharField(choices=[('template1', 'icon typo 2 line +slogan'), ('template2', 'Icon + Typo Long'), ('template3', 'Large Icon + Typo 2 line + Slogan'), ('template4', 'Icon + Typo short + Slogan'), ('template5', 'Icon + Typo short'), ('template6', 'Icon + Typo Long тАУ 1'), ('template7', 'Icon + Typo Long + Slogan')], default='template2', max_length=15),
        ),
    ]
