# Generated by Django 3.0.7 on 2020-08-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_svg_post_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='svg_post',
            old_name='templates',
            new_name='template',
        ),
    ]
